-- phpMyAdmin SQL Dump
-- version 4.1.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Giu 14, 2015 alle 18:24
-- Versione del server: 5.1.71-community-log
-- PHP Version: 5.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `my_genesisgym`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `categories`
--

CREATE TABLE IF NOT EXISTS `categories` (
  `name` varchar(30) NOT NULL,
  `description` text NOT NULL,
  `page` text NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dump dei dati per la tabella `categories`
--

INSERT INTO `categories` (`name`, `description`, `page`) VALUES
('Aqua', 'Water aerobics (waterobics, aquatic fitness, aquafitness, aquafit) is the performance of aerobic exercise in fairly shallow water such as in a swimming pool. Done mostly vertically and without swimming typically in waist deep or deeper water, it is a type of resistance training. Water aerobics is a form of aerobic exercise that requires water-immersed participants. Most water aerobics is in a group fitness class setting with a trained professional teaching for about an hour. The classes focus on aerobic endurance, resistance training, and creating an enjoyable atmosphere with music. Different forms of water aerobics include: aqua Zumba, water yoga, aqua aerobics, and aqua jog.', 'http://genesisgym.altervista.org/cat/Aqua.html'),
('Athletic Training', 'Athletic training has been recognized by the American Medical Association (AMA) as an allied health care profession since June 1991.<br><br>\r\nAs defined by the Strategic Implementing Team of the National Athletic Trainers'' Association (NATA) in August 2007.<br><br>\r\n<i>"Athletic training is practiced by athletic trainers, health care professionals who collaborate with physicians to optimize activity and participation of patients and clients. Athletic training encompasses the prevention, diagnosis, and intervention of emergency, acute and chronic medical conditions involving impairment, functional limitations and disabilities."</i><br><br>\r\nAn athletic trainer functions as an integral member of the health care team in clinics, secondary schools, colleges and universities, professional sports programs, and other athletic health care settings.\r\n', 'http://genesisgym.altervista.org/cat/AthleticTraining.html'),
('Ballet Barre', 'In ballet, barre work includes both slow and fast exercises, which both serve to strengthen muscles. Slow exercises are typically performed first, to stretch and warm up muscles, and to focus on proper body form, whereas fast exercises condition dancers to maintain precise ballet technique while moving. Each exercise has a specific purpose, such as to strengthen feet and legs, increase extension, improve flexibility, and develop ballon. Proper form (posture, positions of feet and arms) is strived for in all exercises.<br><br>\r\nA barre helps dancers by providing a means of stability and balance and, consequently, barre work often comprises a significant portion of the beginning dancer''s class. It is an essential tool when first learning foot placement technique, and also for beginning pointe dancers, who have not yet developed the strength and technique needed for pointe work. The barre continues to be an important tool in all levels of ballet. Barre work helps dancers prepare for partnering, with the barre simulating the support of a real partner. <br><br>\r\nWhen used for promoting general fitness, barre exercises may incorporate a wide variety of activities to increase stamina, flexibility and strength, including ballet movements that require balance and stimulate the core such as pliés and pirouettes.', 'http://genesisgym.altervista.org/cat/BalletBarre.html'),
('Dance', 'Dance is the art of movement of the body, usually rhythmically and to music, using prescribed or improvised steps and gestures. "A dance" is any one prescribed sequence of such movements, or the music to which it is performed, or an event at which it takes place.[1] Dance may also be regarded as a form of nonverbal communication recognisable in other animals; in bee dances and behaviour patterns such as mating dances.<br><br>\r\nDance can be categorized and described in various ways. It may be analysed purely by its choreography, its repertoire of movements, or it may be classified according to its time or place of origin. Yet study reveals many generic similarities in many different times and places.<br><br>\r\nMartial arts kata are often compared to dances, and sports such as gymnastics, figure skating and synchronized swimming are generally thought to incorporate dance.\r\n', 'http://genesisgym.altervista.org/cat/Dance.html'),
('Exercise Physiology', 'Exercise physiology is the study of the acute responses and chronic adaptations to a wide range of physical exercise conditions. In addition, many exercise physiologists study the effect of exercise on pathology, and the mechanisms by which exercise can reduce or reverse disease progression. Accreditation programs exist with professional bodies in most developed countries, ensuring the quality and consistency of education. In Canada, one may obtain the professional certification title – Certified Exercise Physiologist for those working with clients (both clinical and non clinical) in the health and fitness industry.<br><br>\r\nAn exercise physiologist''s area of study may include but is not limited to biochemistry, bioenergetics, cardiopulmonary function, hematology, biomechanics, skeletal muscle physiology, neuroendocrine function, and central and peripheral nervous system function. Furthermore, exercise physiologists range from basic scientists, to clinical researchers, to clinicians, to sports trainers.', 'http://genesisgym.altervista.org/cat/ExercisePhysiology.html'),
('Group Fitness', 'Group Fitness classes are fantastic for those who love working out in a motivational setting with others. All of the Group Fitness classes are lead by a Certified Group Fitness Instructor and are 30, 45, or 60 minutes long. Classes are held right here in the Rec Center! Classes are drop-in style, so you can attend as many as you want without registering before hand. Try one today with our One Class Pass! Pick yours up at the front desk.', 'http://genesisgym.altervista.org/cat/GroupFitness.html'),
('Indoor Cycling', 'Indoor cycling, as an organized activity, is a form of exercise with classes focusing on endurance, strength, intervals, high intensity (race days) and recovery, and involves using a special stationary exercise bicycle with a weighted flywheel in a classroom setting. It is commonly called spinning.<br><br>\r\nClasses generally use specialized stationary bicycles. Features include a mechanical device to modify the difficulty of pedalling, specially shaped handlebars, and multiple adjustment points to fit the bicycle to a range of riders. Many have a weighted flywheel, which simulates the effects of inertia and momentum when riding a real bicycle. The pedals are equipped with toe clips as on sports bicycles to allow one foot to pull up when the other is pushing down. They may alternatively have clipless receptacles for use with cleated cycling shoes. Padded shorts aid comfort and avoid the chafing caused by the sewn seams in underwear.', 'http://genesisgym.altervista.org/cat/IndoorCycling.html'),
('Indoor Rowing', 'Indoor rowing is taking off across the country! Whether your goals are to stay in shape, develop your fitness, or even compete in tournaments, Indoor Rowing can help you get there.<br><br>\r\nAs well as being a low-impact way to give yourself a full-body workout, Indoor Rowing also offers you the opportunity to hone your rowing technique and develop your drive and focus, achieving real, tangible results in the process.<br><br>\r\nCompetitions, classes, and fund-raising challenges now take place in gyms, schools, and sports clubs throughout the US. Take a look around and discover more about the positive impact that Indoor Rowing can have on your life in and outside of our sport.', 'http://genesisgym.altervista.org/cat/IndoorRowing.html'),
('Life Coaching', 'Life coaching draws upon a variety of tools and techniques from other disciplines such as sociology, psychology, Neuroscience, positive adult development and career counseling with an aim towards helping people identify and achieve personal goals. Specialty life coaches may have degrees and may have studied psychological counseling, hypnosis, dream analysis, divination, marketing, Neuro Linguistic Programming, Affirmations, Auditing and other areas relevant to providing guidance, however life coaches are not necessarily therapists, consultants, sports instructors or health care providers and psychological intervention and business analysis may lie outside the scope of some coaches'' work.', 'http://genesisgym.altervista.org/cat/LifeCoaching.html'),
('Martial Arts', 'Martial arts are codified systems and traditions of combat practices, which are practiced for a variety of reasons: self-defense, competition, physical health and fitness, entertainment, as well as mental, physical, and spiritual development.<br><br>\r\nAlthough the term martial art has become associated with the fighting arts of eastern Asia, it originally referred to the combat systems of Europe as early as the 1550s. The term is derived from Latin, and means "arts of Mars", the Roman god of war. Some authors have argued that fighting arts or fighting systems would be more appropriate on the basis that many martial arts were never "martial" in the sense of being used or created by professional warriors.', 'http://genesisgym.altervista.org/cat/MartialArts.html'),
('Mind Body', 'The term mind-body exercise comes to the fitness industry from the field of mind-body medicine. According to the Mind/Body Medical Institute in Chestnut Hill, Massachusetts, mind-body medicine is based on the <i>“inseparable connection between the mind and body—the complicated interactions that take place between thoughts, body and the outside world.”</i><br><br>\r\nToday’s strong focus on mind-body medicine had its beginnings as early as the 1940s and 1950s, when Hans Selye, MD, popularized the concept of stress and the “fight or flight” response in modern medicine. The field has evolved steadily since the early 1970s, which saw the emergence of body therapies, along with pioneering studies on the psychological impacts of exercise. That same decade, Herbert Benson, MD, from Harvard University, coined the term relaxation response to describe how changes in states of mind could effect changes in the body. Benson’s research documenting the relaxation response was based on studies of people who engaged in transcendental meditation. His findings provided research-based evidence that mental changes resulting from meditation could bring about beneficial physiological changes.', 'http://genesisgym.altervista.org/cat/MindBody.html'),
('Nutrition', 'The golden rule of any fitness program or lifestyle is that nutrition is king. Poor recovery between workouts can usually be traced to a lack of nutritional support. Muscle fatigue during a workout is normal; waking up and feeling like your body took a beating is not.<br><br>\r\nWithout a proper nutrition regimen to complement your active lifestyle, you could be wasting your efforts, seeing the slowest—or non-existent—progress, or worse, putting your entire body at risk for a bevy of dysfunction, including injuries, hormonal imbalances, and adrenal fatigue.', 'http://genesisgym.altervista.org/cat/Nutrition.html'),
('Pilates', 'Pilates is a physical fitness system developed in the early 20th century by the Greek German-born Joseph Pilates. It is especially practiced in the United States (where Pilates lived, developed and taught his method) and the United Kingdom (where he lived and taught early stages of his method). As of 2005, there were 11 million people practicing the discipline regularly and 14,000 instructors in the United States.<br><br>\r\nIn his book <i>”Return to Life through Contrology”</i>, Joseph Pilates presents his method as the art of controlled movements, which should look and feel like a workout (not a therapy) when properly manifested. If practiced with consistency, Pilates improves flexibility, builds strength and develops control and endurance in the whole human body. It puts emphasis on alignment, breathing, developing a strong powerhouse, and improving coordination and balance. Pilates'' system allows for different exercises to be modified in range of difficulty from beginner to advanced or to any other level, and also in terms of the instructor and practitioner''s specific goals and/or limitations. Intensity can be increased over time as the body conditions and adapts to the exercises.', 'http://genesisgym.altervista.org/cat/Pilates.html'),
('Weight Training', 'Weight training is a common type of strength training for developing the strength and size of skeletal muscles. It uses the weight force of gravity (in the form of weighted bars, dumbbells or weight stacks) to oppose the force generated by muscle through concentric or eccentric contraction. Weight training uses a variety of specialized equipment to target specific muscle groups and types of movement.<br><br>\r\nSports where strength training is central are bodybuilding, weightlifting, powerlifting, and strongman, Highland games, shotput, discus throw, and javelin throw. Many other sports use strength training as part of their training regimen, notably; mixed martial arts, American football, wrestling, rugby football, track and field, rowing, lacrosse, basketball, baseball and hockey. Strength training for other sports and physical activities is becoming increasingly popular.', 'http://genesisgym.altervista.org/cat/WeightTraining.html'),
('Yoga', 'Yoga is an Indian physical, mental, and spiritual practice or discipline. There is a broad variety of schools, practices and goals in Hinduism, Buddhism (including Vajrayana and Tibetan Buddhism) and Jainism. The best-known are Hatha yoga and Raja yoga.<br><br>\r\nThe origins of Yoga have been speculated to date back to pre-Vedic Indian traditions, but most likely developed around the sixth and fifth centuries BCE, in ancient India''s ascetic circles, which are also credited with the early sramana movements. The chronology of earliest texts describing yoga-practices is unclear, varyingly credited to Hindu Upanishads and Buddhist Pāli Canon, probably of third century BCE or later. The Yoga Sutras of Patanjali from first half of 1st millennium CE is one of a key surviving major texts on Yoga. Hatha yoga texts emerged around 11th century CE, and in its origins was related to Tantrism.', 'http://genesisgym.altervista.org/cat/Yoga.html');

-- --------------------------------------------------------

--
-- Struttura della tabella `contacts`
--

CREATE TABLE IF NOT EXISTS `contacts` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `contactType` text NOT NULL,
  `data` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;

--
-- Dump dei dati per la tabella `contacts`
--

INSERT INTO `contacts` (`id`, `contactType`, `data`) VALUES
(1, 'Address', '3002 Main St., Santa Monica, CA 90401'),
(2, 'Phone:', '(310) 458-8301'),
(3, 'Fax:', '(310) 458-2263'),
(4, 'E-Mail:', 'mail@genesisgym.com'),
(5, 'Parking:', 'The corner of Marine and Main Street'),
(6, 'latitude', '33.998301'),
(7, 'longitude', '-118.480099');

-- --------------------------------------------------------

--
-- Struttura della tabella `courses`
--

CREATE TABLE IF NOT EXISTS `courses` (
  `name` varchar(30) NOT NULL,
  `category` varchar(30) NOT NULL,
  `difficulty` int(11) NOT NULL,
  `description` text NOT NULL,
  `instr1` int(11) NOT NULL,
  `instr2` int(11) NOT NULL,
  `videourl` text NOT NULL,
  `page` text NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dump dei dati per la tabella `courses`
--

INSERT INTO `courses` (`name`, `category`, `difficulty`, `description`, `instr1`, `instr2`, `videourl`, `page`) VALUES
('Beginners Yoga', 'Yoga', 1, 'An introduction to yoga: learn the philosophy of Yoga and basic poses in this tranquil class. You will begin to build the foundation for your yoga practice as you gain flexibility, strength, balance, and the relationship of movement and breath. Yoga is perfect for overall well being.', 3, 4, 'https://www.youtube.com/embed/2_SE2gQwXoo', 'http://genesisgym.altervista.org/course/BeginnersYoga.html'),
('Body Building', 'Weight Training', 3, 'This class will condition your muscular strength and endurance. Body sculpting is a total body workout with a method of instructor’s choice of weights/resistance equipment.', 1, 2, 'https://www.youtube.com/embed/q61Pud_iTwQ', 'http://genesisgym.altervista.org/course/BodyBuilding.html'),
('Boxing', 'Martial Arts', 2, 'Traditional boxing techniques with a professional boxing trainer, train as the professionals do without the ring.\r\nBoxing is a combat sport and martial art in which two people fight using their fists for competition.\r\nBoxing is typically supervised by a referee engaged in during a series of one- to three-minute intervals called rounds, and boxers generally of similar weight. There are four ways to win; if the opponent is knocked out and unable to get up before the referee counts to ten seconds (a knockout, or KO) or if the opponent is deemed too injured to continue (a Technical Knockout, or TKO), if an opponent is disqualified for breaking a rule, or if there is no stoppage of the fight before an agreed number of rounds, a winner is determined either by the referee''s decision or by judges'' scorecards.', 1, 2, 'https://www.youtube.com/embed/m-ITVandGJk', 'http://genesisgym.altervista.org/course/Boxing.html'),
('Cardio Conditioning', 'Exercise Physiology', 2, 'Cardio Conditioning: An athletic approach to a total body workout program with multiple sports conditioning and fitness techniques which provide lasting strength and energy as well as a unique platform for achieving weight loss goals and lean body mass.', 5, 6, 'https://www.youtube.com/embed/hvGw31Fi9Q8', 'http://genesisgym.altervista.org/course/CardioConditioning.html'),
('Fat Burn', 'Exercise Physiology', 2, 'Burn fat and sweat away the pounds with high intensity training, using bodyweight and free weight resistance exercises', 5, 6, 'https://www.youtube.com/embed/52uvwCi03yE', 'http://genesisgym.altervista.org/course/FatBurn.html'),
('Muay Thai', 'Martial Arts', 3, 'Muay Thai / Thaiboxing / Kickboxing is the national sport of Thailand. It is also referred to as “the Art of Eight Limbs” because you are using your hands, elbows, knees, and legs. Muay Thai training develops your cardio-vascular system, endurance, strength, flexibility, speed, and self confidence. It will also help you relieve stress, lose weight, and teach you how to defend yourself.\r\nMuay Thai is known for it’s intense training routines, and the challenge is not easy. You will require discipline and dedication to endure it, and I invite you to rise to the challenge. Muay Thai not only teaches skill and physical strength; but also helps develop a strong personal character.', 7, 8, 'https://www.youtube.com/embed/yDlejxMskZ0', 'http://genesisgym.altervista.org/course/MuayThai.html'),
('Pilates', 'Pilates', 1, 'Pilates is group of exercises developed by Joseph Pilates that are designed to strengthen and tone your muscles through core body training.', 3, 4, 'https://www.youtube.com/embed/JxGE5SYVYE4', 'http://genesisgym.altervista.org/course/Pilates.html'),
('Pilates Reformer', 'Pilates', 2, 'This technique applies Pilates movements on the reformer. Spring-loaded resistance training will increase range of motion and flexibility, while building muscle strength without adding bulk. This technique is a full body workout, originating from the core.', 3, 4, 'https://www.youtube.com/embed/WqYHzSsq2Jg', 'http://genesisgym.altervista.org/course/PilatesReformer.html'),
('Power Yoga', 'Yoga', 1, 'This class is perfect for beginning students and for students wishing to practice at a moderate pace, as it combines movement, breath, and meditation to foster flexibility, relaxation, and self-awareness. This is a wonderful class to learn and experience principles for de-stressing your life and reviving your spirit!', 7, 8, 'https://www.youtube.com/embed/tFk7SVtjs38', 'http://genesisgym.altervista.org/course/PowerYoga.html'),
('Step Force', 'Athletic Training', 3, 'Step aerobics with boot camp style drills, utilizing dumbbells, body bars and intervals that are sure to make you sweat and get ripped results.', 9, 10, 'https://www.youtube.com/embed/Rm64cN5rAXE', 'http://genesisgym.altervista.org/course/StepForce.html'),
('Vinyasa Yoga', 'Yoga', 2, 'This powerful flowing form of yoga is infused with breathing practices as well as the exploration of your own personal power with held postures, meditation and freedom of movement. Experience true liberation!', 3, 4, 'https://www.youtube.com/embed/LwP8G5ot-kg', 'http://genesisgym.altervista.org/course/VinyasaYoga.html'),
('Zumba', 'Dance', 2, 'Zumba is a Latin inspired dance/fitness program. The word Zumba is derived from a Columbian word meaning to move fast and have fun. Combining steps like Salsa, Cha-cha, Meringue a high energy fusion of Latin and International music, Zumba is a unique and effective program that everyone can do.', 9, 10, 'https://www.youtube.com/embed/Vf0q6qtThF4', 'http://genesisgym.altervista.org/course/Zumba.html'),
('Krav Maga', 'Martial Arts', 2, 'Like any self-defense training or martial art study, Krav Maga cannot make you invincible.\r\n\r\nBut what it can do for you is help build fundamental confidence, incrementally and systematically. Krav Maga training strives to take hesitation (uncertainty) out of dangerous or threatening situations. This type of discipline often extends to other parts of life.\r\n\r\nOur students claim they stand straighter, speak with more authority and develop a “sense” about them that emphatically states: “I can take care of myself!”\r\n', 3, 4, 'https://www.youtube.com/embed/5Y8dtOiJ708', 'http://genesisgym.altervista.org/course/KravMaga.html'),
('Brazilian Jiu Jitsu', 'Martial Arts', 3, 'BJJ teaches that a smaller, weaker person can successfully defend against a bigger, stronger assailant by using leverage and proper technique—most notably, by applying joint-locks and chokeholds to subdue or defeat his or her opponent.\r\n\r\nIt is a fantastic martial art for law enforcement as well as self-defense for women or men. Brazilian Jiu-Jitzu can stand alone as a single martial art, or be incorporated into additional fight disciplines to amplify your existing skills.\r\n', 2, 8, 'https://www.youtube.com/embed/USB_X-U2zZs', 'http://genesisgym.altervista.org/course/BrazilianJJ.html'),
('Boot Camp', 'Athletic Training', 3, 'A fitness boot camp is a type of physical training program conducted by gyms, personal trainers, and former military personnel. These programs have been increasing in popularity for the past several years.\r\n\r\nBoot Camp training often combines running, interval training, and many other exercises using weights and/or body weight to lose body fat, increase cardiovascular efficiency, increase strength, and help people get into a routine of regular exercise. Many programs offer nutrition advice as well. It is called "boot camp" because it trains groups of people, typically outdoors, and may or may not be similar to military basic training.\r\n\r\nThe term ''boot camp'' is currently used in the fitness industry to describe group fitness classes that promote fat loss, camaraderie and team effort. They are designed to push people a little bit further than they would normally push themselves in the gym alone. Boot Camps are often organized outdoors in parks using bodyweight exercises like push ups, squats, suspension training and burpees, interspersed with running and competitive games. The idea is that everyone involved works at their own pace as they team up and work towards one goal, either in pairs, small teams of three or four, or even two teams head on.\r\n\r\nBoot camps provide social support for those taking part. This provides a different environment for those exercisers who get bored in a gym and so find it hard to develop a habit of exercise. Participants make friends and socialize as they exercise, although how strict the trainers or drill instructors in charge can be will depend on the company running the camp. Members of fitness boot camps are usually tested for fitness on Day 1 and then retested at the end of the camp, which usually runs for between 4–6 weeks.\r\n\r\nFitness bootcamps are often based on the military style of training. Usually held outdoors the activities include jogging, sprinting, plyometrics, push-ups, pull-ups, squats, lunges, suspension training and a variety of other calisthenic exercises. An advantage of a bootcamp is that the large group dynamic will often help motivate the participants.', 5, 4, 'https://www.youtube.com/embed/NEeLircu3Qk', 'http://genesisgym.altervista.org/course/BootCamp.html'),
('Abs and Butt', 'Group Fitness', 1, 'Strengthen and tone your core and glutes through a variety of resistance training exercises designed to target the areas which suppport your lower back and provide the foundation for your body.', 1, 10, 'https://www.youtube.com/embed/TwCBr0Dqlms', 'http://genesisgym.altervista.org/course/AbsandButt.html'),
('Capoeira', 'Martial Arts', 2, 'Capoeira (Portuguese pronunciation: [kapuˈejɾɐ]) is an Afro-Brazilian art form that combines elements of martial arts, music, and dance. It was created in Brazil by African slaves by mixing the many fighting styles from many of their tribes, sometime after the sixteenth century.[1] It was developed in the region of Quilombo dos Palmares, located in the Brazilian state of Alagoas, which was the state of Pernambuco before dismemberment, and has had great influence on Afro-Brazilian generations, with strong presence in the states of Bahia, Pernambuco, Rio de Janeiro and São Paulo. Participants form a roda, or circle, and take turns either playing musical instruments (such as the Berimbau), singing, or ritually sparring in pairs in the center of the circle. The sparring is marked by fluid acrobatic play, feints, takedowns, and with extensive use of leg sweeps, kicks, and headbutts. Less frequently used techniques include elbow strikes, slaps, punches, and body throws. Its origins and purpose are a matter of debate, with theories ranging from views of Capoeira as a uniquely Brazilian folk dance with improvised fighting movements to claims that it is a battle-ready fighting form directly descended from ancient African techniques.', 6, 3, 'https://www.youtube.com/embed/6H0D8VaIli0', 'http://genesisgym.altervista.org/course/Capoeira.html'),
('Spin', 'Indoor Cycling', 2, 'Spin® Experience: If you love challenges and biking this is the class for you. Spinning® has been around for years however seems to be the latest craze in the fitness world. Burn calories as you tone your legs through various levels of spinning® on a stationary bike with uplifting music. A true challenging workout experience\r\n\r\nSpin Flex: For those of you who want more than a spin class, spin-flex incorporates cardio training as well as a total body workout using resistance bands, free weights and body weight.', 4, 7, 'https://www.youtube.com/embed/2S6eMCxF9Gw', 'http://genesisgym.altervista.org/course/Spin.html'),
('Kickboxing', 'Martial Arts', 2, 'Kickboxing (in Japanese キックボクシング kikkubokushingu) is a group of stand-up combat sports based on kicking and punching, historically developed from karate, Muay Thai, Taekwondo and Western boxing. Kickboxing is practiced for self-defense, general fitness, or as a contact sport. Japanese kickboxing originates in the 1960s, with competitions held since then. American kickboxing originates in the 1970s and brought to prominence in September 1974 when the Professional Karate Association (PKA) held the first World Championships. Historically, kickboxing can be considered a hybrid martial art formed from the combination of elements of various traditional styles. This approach became increasingly popular since the 1970s, and since the 1990s, kickboxing has contributed to the emergence of mixed martial arts via further hybridization with ground fighting techniques from Brazilian jiu-jitsu and Folk wrestling.', 1, 11, 'https://www.youtube.com/embed/H-JFcV6FFrU', 'http://genesisgym.altervista.org/course/Kickboxing.html');

-- --------------------------------------------------------

--
-- Struttura della tabella `instructors`
--

CREATE TABLE IF NOT EXISTS `instructors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `surname` varchar(20) NOT NULL,
  `bio` text NOT NULL,
  `page` text NOT NULL,
  `iotmCheck` tinyint(1) NOT NULL DEFAULT '0',
  `iotmBio` text NOT NULL,
  `facebook` text NOT NULL,
  `twitter` text NOT NULL,
  `imgurl` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=11 ;

--
-- Dump dei dati per la tabella `instructors`
--

INSERT INTO `instructors` (`id`, `name`, `surname`, `bio`, `page`, `iotmCheck`, `iotmBio`, `facebook`, `twitter`, `imgurl`) VALUES
(1, 'Wellington', 'Paim', 'College of Sports Medicine, Sao Paulo Brazil\r\n\r\nSenac Personal Training Academy, San Paolo, Brazil\r\n\r\nNFPT and AFI Personal Training Certified, NY, USA\r\n\r\nWellington Paim, originally from Sao Paolo, Brazil, has an extensive background in Personal Training for over 12 years. Wellington specializes in Strength Training and Conditioning and is famous for his extreme workouts and total body transformation.\r\n\r\nHis portfolio includes Celebrities, Elite Athletes and corporate executives of which he has helped to obtain and maintain their personal and professional goals. There are over 100 client testimonials about their experience and total transformation Wellington has achieved for them. Wellington’s success is based on his exercise routines and great understanding and knowledge of nutrition that he implements in his regimen. Wellington Paim guarantees results only if you guarantee dedication!\r\n', 'http://genesisgym.altervista.org/instructor/WellingtonPaim.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/wellingtonpaim.jpg'),
(2, 'Sandor', 'Margittai', 'Sandor “Sasha” Margittai is a certified personal trainer, all natural drug free men’s physique competitor and fitness model. An athlete all his life, Sandor grew up as a gymnast and later ran track and played high school basketball. In 2010 he decided to re-locate to New York City as he wanted to fulfill his dream to build a fitness career in the United States. Sandor has worked with actors, singers, dancers and artists. \r\nHe has been helping people lose weight, gain quality muscle tone and shape at any age with his motivating advice, diets, healthy recipes, exercise tips, workout videos and more. He''ll supplement your workouts with a comprehensive nutrition program to kick start your metabolism. This incorporates a food plan to feed muscle, shed fat and specifically tailor your body''s needs with frequently-monitored and measurable goals.\r\n\r\nAs a certified personal trainer, he has active professional training experience in health and wellness programs and pledges to achieve maximum results catering to a wide range of clientele. Sandor specializes in strength conditioning, proper stretching techniques, weight loss and nutrition. His mixes of proven training methods and creative new approaches make him a unique choice you won''t regret. He is known for body transformations and his clients are real life examples of his work. He believes that in order to get the most out of the body, one must first give the body what it needs. This has been shown to be much more effective and efficient for sustaining results long term. And yes, you can look your best and feel great too!', 'http://genesisgym.altervista.org/instructor/SandorMargittai.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/sandormargittai.jpg'),
(3, 'Jenna', 'Tomsko', 'Jenna Tomsko has always loved working out, and she''s thrilled that her career allows her to share that enthusiasm with others. From her days of doing Jane Fonda aerobics tapes along with her mother at age 5 to her newly discovered addiction to Cross Fit and Olympic weightlifting, she always finds a way to give even the most anti-gym client something to love about working out. After moving to New York in 2009 to pursue theater, Jenna attended the American Academy of Personal Training, and got her start training at Crunch. She''s excited to bring her style of "integrated training" to Club Fitness NY, combining elements of power lifting, metabolic conditioning, kettle bell training, and traditional resistance training programs. She is dedicated to teaching functional movement and emphasizing strength, power, stamina, and fitness over achieving the perfect body weight or dress size (although it is always a welcome side effect!). She is also a certified kettle bell instructor, and specializes in pre- and post-natal fitness. She is currently pursuing a Cross -Fit certification, and will compete in the 2012 Cross Fit Games Sectional.', 'http://genesisgym.altervista.org/instructor/JennaTomsko.html', 1, '<b>When did you start practicing yoga?</b><br><br>\r\nI actually grew up surrounded by the practice. My grandma taught at a yoga studio and I remember sitting\r\nin cow face when I was very young. The ladies all “oohed” because I could grab my fingers behind my back.\r\nAs I age, my goal is to maintain a youthful flexibility both of body and of mind.<br><br>\r\n<b>What has yoga brought to your life?</b><br><br>\r\nYoga has provided me a deeper understanding of the human experience. It is a liberation teaching. It\r\nteaches us that we are unlimited, free, and that we have not yet tapped into our true potential. Yoga\r\nencourages us to identify what is not serving us in life, in love, and to find the courage to let it go. It is\r\nthe gateway to tune in towhat is real and tune everything else out.<br><br>\r\n<b>Why did you become a yoga instructor?</b><br><br>\r\nI initially became a yoga instructor to uplift the community of young women that surrounded me. I began\r\nteaching at a small studio next to a very large college campus and I found a passion for cultivating a\r\ncommunity that uplifts one another. I know how impactful the words “you are beautiful” can be and I\r\nmade it my mission tonot only tell my students this but to repeat it enough times that they began\r\nto believe it. I repeated it until it began to replace whatever was there before. Now I focus on yoga\r\noutreach, victims of sexual assault, eating disorders, and maintaining a healthy body image.\r\n', '', '', 'http://genesisgym.altervista.org//images/instr/jennatomsko.jpg'),
(4, 'Dennis', 'Toral', 'Dennis Toral is one of Club Fitness’ most fierce and dedicated trainers. Now 29 years old, Dennis began his quest in martial arts at the age of 15 learning Judo, Jiu Jitsu, and Karate before settling into Muay Thai and Boxing.\r\n\r\nAfter an explosive career in both boxing and mixed martial arts, Dennis transitioned from fighter to mentor. Today, Dennis’ prime motivation is helping his students meet their goals through vigorous training.\r\n', 'http://genesisgym.altervista.org/instructor/DennisToral.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/dennistoral.jpg'),
(5, 'Craig', 'Groshans', '“When I was 21 I joined a gym and started lifting weights. I didn’t see many results for the first year, mainly because I applied myself half-heartedly and my gym schedule was sporadic, but also because I just didn’t know what the heck I was doing! I didn’t understand the principles or the science behind it all.\r\n\r\n“One day I was in a book store and I came across Arnold Schwarzenegger’s ‘Encyclopedia of Modern Bodybuilding’. It was the first book of dozens I would devour. As I learned the proper way to train and applied these new techniques safely and efficiently, I began to see drastic changed in my body! Amazing, how quickly it came together once I had my head and heart in the right place! Within a year my body had undergone a tremendous transformation. I looked great, felt great and for the first time in my life I realized that confidence, happiness, peace of mind…all these things could be mine. It changed me in more ways than my newly discovered strength and determination. It healed emotional wounds I wasn’t even aware I’d had and helped me grow to be the man I am today.\r\n\r\n“I realized that I wanted to help others the same way. I wanted to share this great newfound energy I could feel bursting from within. I chose a school, studied hard and became a certified personal trainer. Now, with 7 years of experience working in the fitness industry, I have honed my skills to a razor edge. I have enjoyed working with people from all walks of life, with a vast array of fitness goals. I look forward to continuing this great work and helping promote the positive energy we all have hidden within!”\r\n\r\nWhatever your fitness goals, I am confident in my ability to assist you in achieving them safely and efficiently, and in as short a timeframe as possible.\r\n\r\nI believe in a holistic approach to life. Everything begins here, in the physical realm. If you look good and feel good it will translate into every aspect of your life. Healthy body=healthy mind. Physically, mentally, emotionally and eve spiritually…exercise and the conscious effort to attain a higher level of fitness will assure balance in every capacity.\r\n\r\nLet me show you.', 'http://genesisgym.altervista.org/instructor/CraigGroshans.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/craiggroshans.jpg'),
(6, 'Bobby', 'Simotas', 'Hello, my name is Bobby Simotas.\r\n\r\nI was born and raised in Astoria, NY and have been in the fitness scene for as long as I can remember. From playing high school sports including: basketball, baseball and soccer to weight training from the early age of seven-teen. By involving myself in the gym scene from such a young age, I have specialized in different methods of training such as: Muscle Building, Weight Loss, Deduction of Body Fat Percentage, Therapeutic Exercises, Building Strength and even Rehabilitation Exercises for those who have just come off injuries, with all this I also carry more than 5 years of experience in a gym facility.  \r\n\r\nI am certified through the National Academy of Sports Medicine and have been a certified personal trainer for over 2 years now, working with all body types, genders and ages. Aside from working in the gym, I also work in a therapy office which allows me to expand my knowledge on the functions of the human body as well as new techniques and methods for improving range of motion and strengthening specific muscle groups.\r\n\r\nMy Philosophy on personal training is focused on two things; the uniqueness of each individual and the positive health and fitness improvements of the individuals total lifestyle. See, everyone is diverse. This is a very important factor in a personal trainer’s ability in getting their client’s to accomplish their optimal level of success. What works for one individual doesn’t mean it will work well for another.\r\n\r\nLet me find out what works best for you!', 'http://genesisgym.altervista.org/instructor/BobbySimotas.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/bobbysimotas.jpg'),
(7, 'Cindy', 'Bryan', 'Cindy is certified as a personal trainer by the American College of Sports Medicine and has her Bachelor of Science in Exercise Physiology. Her passion for fitness comes from years of cross-country running and an extreme interest in the body’s response to exercise.\r\n\r\nOriginally from California, she is loving New York''s fitness industry.\r\n\r\nWhen it comes to training, she firmly believes that “the body achieves what the mind believes.” If you can believe it, you can achieve it! All it takes is some hard work, dedication, and the right program. Whether its bodybuilding, weight loss, toning, or event training, she is dedicated to working with highly motivated individuals to help them achieve their fitness goals', 'http://genesisgym.altervista.org/instructor/CindyBryan.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/cindybryan.jpg'),
(8, 'Alex', 'Hadjicharalambous', 'For as long as I can remember I have always been active, playing sports, running and just enjoying life. Playing soccer introduced me to training at an early age. Weight and endurance training helped me on and off the playing field. I took this love of fitness and became a personal trainer.\r\n\r\nI am certified through the National Academy of Sports Medicine (NASM) and have been a certified personal trainer for over a year now. My goal as a personal trainer is to motivate, inspire, and educate others about the benefits of exercising and living a healthy lifestyle.\r\n\r\nHealth and fitness is more than just your appearance; exercising makes us feel better and live healthier. With patience and persistence, anyone can achieve realistic goals, including high self-esteem, confidence, and the body you desire.\r\n\r\nI strive to create a personal relationship with all my clients. My philosophy on personal training is to provide encouragement, confidence, motivation, and strength, to help you reach your fitness goals!', 'http://genesisgym.altervista.org/instructor/AlexHadjicharalambous.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/alexhadjicharalambous.jpg'),
(9, 'Laura', 'Ramos', 'Laura is certified by the International Sports Sciences Association and comes to us from Los Angeles, CA where she trained and taught classes with some of LA’s top celebrity trainers.\r\n\r\nHaving just moved to New York, and being a fluent Spanish speaker, she enjoys the cultural diversity of the city, reinforcing the fact that each and every body is different. Everyone requires a unique approach to achieve his or her specific goal. Having worked with all ages, body types, experience levels, Laura’s priority is to make everyone feel comfortable, whether it be in the gym by teaching you how to correctly utilize the tools laid for you at the facility, or to help you feel comfortable in your own body. Her goal as a trainer is to motivate, push, and guide you by focusing on fitness as a way of life and not just a means of attaining a number on the scale.\r\n\r\nHer appreciation for athletics began just a few years ago when she started to take up running and racing, suddenly realizing the gratification you get when you push your body to a certain degree and accomplish a goal you set out to achieve. That is when she learned the old adage ‘mind over matter’ is nothing but true.\r\n\r\nLaura loves to challenge you and keep things interesting, always pushing your body to its proper limits to get your desired results. Get the most out of your sessions with a high energy workout, practicing the newest moves while never doing the same workout twice. Help shed your fear of the weight room and resistance machines and explore new ways of enhancing your body while boosting your confidence at the same time.\r\n\r\nShe’ll make you want to come to the gym, not dread it- It should be fun, not a chore! It’s always a good time.', 'http://genesisgym.altervista.org/instructor/LauraRamos.html', 0, '', '', '', 'http://genesisgym.altervista.org//images/instr/lauraramos.jpg'),
(10, 'Caio', 'Dias', 'Optimal health is in all of our birth rights. It is my humble opinion life should be lived with an abundant amount of luxurious energy. Somewhere along the line, we may have forgotten foundational principles that keep us healthy and vital. Its my job and passion to help remind you of these concepts while also opening ideas to new ones, all to add to your personal arsenal of health and wellness.\r\n\r\nA lifetime experience of athlticism, exercise and participating in a high caliber traveling soccer team, gave me the experience and wisdom to attain knowledge and skills that now allows me to be able to share with other. My continuous thirst for knowledge is exceptional and paramount in my goal of comprehending fitness and well-being as a whole.\r\n\r\nTo restore our health is to restore health to our ecosystem and Mother Earth, for the two are inextricably linked. To get healthy we must begin to think right and develop new habits that are worth attaining. \r\n\r\nIt''s not hard to be fit, vital, feel productive and to have a beatiful body, it''s just a choice. Famous Australian business consultant Brad Sugar Says, "the formula for change is when the desire for change is greater than the resistance for change." My holistic-minded approach to life realizes that our health is not primarily due to our physical well being but also our emotional and spiritual state. I invite you to follow the simple life changing principles I can share with you so that we can all set a good example for the next generation. We owe it to ourselves and to our children to be healthy and vital. You deserve nothing but the best.', 'http://genesisgym.altervista.org/instructor/CaioDias.html', 0, '', '', '', 'http://genesisgym.altervista.org/images/instr/caiodias.jpg');

-- --------------------------------------------------------

--
-- Struttura della tabella `intro`
--

CREATE TABLE IF NOT EXISTS `intro` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page` varchar(20) NOT NULL,
  `description` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

--
-- Dump dei dati per la tabella `intro`
--

INSERT INTO `intro` (`id`, `page`, `description`) VALUES
(1, 'location', '<b>Genesis Gym:</b> 3002 Main St,\r\nSanta Monica, CA 90405\r\n\r\n<b>Parking:</b> Corner of Marine and Main\r\nWe validate for 1.5 hours\r\n\r\n<b>Phone Number:</b> 310-314-0220\r\n\r\n<b>Email:</b> info@220fit.com '),
(3, 'instructor', 'A personal trainer is a fitness professional involved in exercise prescription and instruction. They motivate clients by setting goals and providing feedback and accountability to clients. Trainers also measure their client''s strengths and weaknesses with fitness assessments. These fitness assessments may also be performed before and after an exercise program to measure their client''s improvements in physical fitness.\r\n\r\nThey may also educate their clients in many other aspects of wellness besides exercise, including general health and nutrition guidelines. Qualified personal trainers recognize their own areas of expertise. If a trainer suspects that one of his or her clients has a medical condition that could prevent the client from safe participation in an exercise program, they must refer the client to the proper health professional for prior clearance.'),
(4, 'iotm', 'Every Month, our costumers vote our instructor, and the one who gets the highest number of votes can procalim himself\r\n"The Instructor of the Month"!\r\nWhat''s the deal with this? Nothing special but some glory on our special website page and some additional infos regarding\r\ntheir own life!'),
(5, 'error', 'The page you requested is not avaiable yet.<br><br>\r\nOur courses are so good that even our IT guys stop hiding behind their PCs and go exercising!');

-- --------------------------------------------------------

--
-- Struttura della tabella `levels`
--

CREATE TABLE IF NOT EXISTS `levels` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `difficulty` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4 ;

--
-- Dump dei dati per la tabella `levels`
--

INSERT INTO `levels` (`id`, `difficulty`) VALUES
(1, 'Easy'),
(2, 'Medium'),
(3, 'Hard');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
